name: React App CI/CD

on:
  push:
    branches:
      - main  # change to your active branch

env:
  IMAGE_NAME: bytesbuddy/ecommerce

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: MUSTAKIMSHAIKH2942/reactecomtestCICD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker Image to Docker Hub
        run: docker push $IMAGE_NAME

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f react-deployment.yaml
          kubectl apply -f react-service.yaml
