name: React CI/CD

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./reactcicd/gitcloneapp/reactecomtestCICD

      - name: Build React app
        run: npm run build
        working-directory: ./reactcicd/gitcloneapp/reactecomtestCICD

      # Optional Docker Image Build and Push
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yourdockerhub/reactcicd-app:latest .
          docker push yourdockerhub/reactcicd-app:latest
        working-directory: ./reactcicd/gitcloneapp/reactecomtestCICD
